### ISSUE TITLE
Can't install permissions library

### ISSUE THREAD

**Issue by anriijmind** [kamranayub/cypress-browser-permissions#23]
Can't install permissions library, it fails
```
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress@1.0.0
npm ERR! Found: cypress@7.2.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^7.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"4.x" from cypress-browser-permissions@1.0.5
npm ERR! node_modules/cypress-browser-permissions
npm ERR!   dev cypress-browser-permissions@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/andrii/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrii/.npm/_logs/2021-04-27T08_06_26_543Z-debug.log`
```

Could you help?

**Comment by kamranayub** [comment]
This is because I need to update the peer dependencies. I will work on doing that.

In the meantime, did you already try this?

> retry npm ERR! this command with --force, or --legacy-peer-deps

Looks like this is the latest npm. 

Let me know if that works. As long as the API hasn't changed, it should be fine.

**Comment by AurelienKun** [comment]
I have this problem too. I have to `--force` the installation which is not great. Any fix soon about this @kamranayub ?

**Comment by kamranayub** [comment]
I'd accept a contribution if someone wants to update the peer (and dev) dependencies in the package.json and has tested it with the latest Cypress. That should be the only thing needed.

Since there's a workaround I have prioritized this, I'll see if I can get to it this week.
