### ISSUE TITLE
Can't get to work on Chrome, Cypress 8.7.0

### ISSUE THREAD

**Issue by Agalias** [kamranayub/cypress-browser-permissions#36]
Hello, I encountered an issue where this plugin just doesn't work with provided instructions on the newer versions of Cypress Chrome. Could someone confirm that it works properly on the Cypress Chrome newer versions please?

**Comment by kamranayub** [comment]
This is working in my PR #37 with Chrome 95 and Cypress 9. What issues are you running into?
